
spring:
  datasource:
    url: jdbc:mysql://192.168.52.102:3306/atm6000db_bfm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ajdts
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 5
      initial-size: 1
      max-wait: 60000
      max-idle: 5
      min-idle: 1

logging:
  config: classpath:logback.xml


mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.serotonin.entity



